project:
  type: website
  output-dir: docs

website:
  title: "Jared Zirkes - Data Science Portfolio"
  description: "A portfolio showcasing my data science projects."
  navbar:
    left:
      - text: "Home"
        href: "index.html"
      - text: "Projects"
        href: "projects.html"
      - text: "Contact"
        href: "contact.html"
