---
title: "My Projects"
output: 
  html_document:
    theme:
      light: flatly
      dark: darkly
    toc: true
    navbar:
      title: "Projects"
      left:
        - text: "Home"
          href: "index.html"
        - text: "Contact"
          href: "contact.html"
---

## Baseball Hall of Fame Analysis

An analysis of BBWAA Hall of Fame voting. This project aims to determine what factors make an MLB player likely to be inducted, analyze Hall of Fame trends over time, and predict likely future inductees. 

- **Technologies used**: Python, Pandas, Scikit-learn, Plotly
- **Key Features**: Data Cleaning, Data Visualization, Predictive Modeling

<a href="https://www.jzirkes.me/Baseball-HOF-Analysis/" target="_blank">View Project</a>

<a href="https://github.com/jaredzrks0/Baseball-HOF-Analysis" target="_blank">Project GitHub</a>

---

## Hand-Made Regression Algorithms

An overview of common regression techniques, and handmade classes for each algorithm. Also includes 3-D plotting of training sets and resulting regression surfaces to understand how each regressor learns data and makes predictions.

<a href="https://www.jzirkes.me/handmade_algorithms" target="_blank">View Project</a>

<a href="https://github.com/jaredzrks0/handmade_algorithms" target="_blank">Project GitHub</a>

---

## Baseball Simulation

Daily Simulation of MLB games. This projet develops a model to predict the outcome of MLB plate appearances based pitch-by-pitch data from Statcast to precict plate appearence results. This model is then leveraged alongside expected lineups, weather, and other outside factors to simulate MLB games and predict outcomes for player statlines.

- **Technologies used**: Python, Pandas, Scikit-learn, TensorFlow
- **Key Features**: Data Cleaning, Feature Engineering, Predictive Modeling, Simulations

<a href="https://github.com/jaredzrks0/MLB-Simulation" target="_blank">Project GitHub</a>

---

## News Recommendation System

A document retrieval system for use in recommending news articles across the political spectrum. The system leverages a COLBERT model checkpoint with further training on a corpus of news articles, and is designed to recommend articles from diverse viewpoints to users based on their preferences.

- **Technologies used**: Python, NLP, Web Scraping
- **Key Features**: Text Similarity, Machine Learning, Recommendation Systems

<a href="https://github.com/jaredzrks0/DSAN5400_final_project" target="_blank">Project GitHub</a>
