---
title: "Progress log"
---

## Process Log

**M: 11-04-2024** 

* Begun data collection by writing code to scrape a table of all MLB Hall of Fame (HOF) members from https://www.baseball-reference.com/awards/hof.shtml

**M: 11-18-2024**

* Continued data collection, scraping annual HOF voting records from each year based on the following webpage: https://www.baseball-reference.com/awards/hall-of-fame-ballot-history.shtml
* Built landing page/about me page

**Sat: 12-7-2024**

* Finished writing data collection classes and begun scraping individual player stats.


**Sun: 12-8-2024**

* Wrote out data collection slide.

**Wed: 12-11-2024**

* Researched study background in more depth and wrote out project landing page
* Finalized Data Collection tab
* Started working through Data Cleaning tab
* Wrote a line of code to filter the many metrics of interest in data cleaning
* Formatted the large markdown table of pitching and batting metrics

**Thu: 12-12-2024**
  
  * Finished Data Cleaning Tab
  * Started work on EDA

**Friday: 12-13-2024**
  
  * Finished EDA
  

**Sat: 12-14-2024**
  
  * Worked through Unsupervised learning tab
  

**Sun: 12-15-2024**
  
  * Finished unsupervised learning tab

**Thu: 12-16-2024**
  
  * Finished project